excluded: 
    - KeePassiumLib/AEXML
    - KeePassiumLib/base32
    - KeePassiumLib/GzipSwift

disabled_rules:
    - force_cast
    - function_body_length
    - type_body_length
    - identifier_name
    - file_length
    - force_try
    - inclusive_language
    - cyclomatic_complexity
    - todo
    - nesting
    - for_where
    - block_based_kvo
    - multiple_closures_with_trailing_closure
    - valid_ibinspectable
    - unavailable_condition
    - shorthand_operator
    - unused_optional_binding
    - trailing_comma
    - unused_closure_parameter
    - opening_brace
    - closure_parameter_position
  
analyzer_rules:
    - unused_import
    - unused_declaration
    - capture_variable

opt_in_rules:
    - block_based_kvo
    - closure_spacing
    - collection_alignment
    - contains_over_first_not_nil
    - empty_string
    - empty_xctest_method
    - explicit_init        
    - first_where
    - identical_operands    
    - literal_expression_end_indentation    
    - nimble_operator
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - private_action    
    - prohibited_super_call
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - redundant_nil_coalescing
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
    - yoda_condition  

type_name:
    max_length: 50

function_parameter_count:
    warning: 8
    error: 10

line_length:
    ignores_interpolated_strings: true
    ignores_urls: true
